name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - merging_branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

#      - name: Run Lint if Script Exists
#        run: |
#            if npm run | grep -q "lint"; then
#              echo "Lint script found. Running npm run lint."
#              npm run lint -- --max-warnings=0
#            else
#              echo "No lint script found in package.json. Skipping lint step."
#            fi

      - name: Build the React app
        run: CI=false npm run build

      - name: Configure Git for gh-pages
        run: |
          git config user.name "elemson"
          git config user.email "toluwanielemosho@gmail.com"
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}